// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("Reactive Streams")]
[assembly: AssemblyCopyrightAttribute("MIT-0")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyVersionAttribute("1.0.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0.0")]
