// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("Reactive Streams")]
[assembly: AssemblyCopyrightAttribute("CC0 1.0 Universal")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyVersionAttribute("1.0.1.0")]
[assembly: AssemblyFileVersionAttribute("1.0.1.0")]
